#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the hostname
# shellcheck disable=SC2154
sudo apt-get update -y
sudo apt-get install -y nginx
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf
sudo service nginx restart
