#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the hostname
# shellcheck disable=SC2154
sudo apt update 
sudo apt install -y nginx
sudo sed -i '/server_name _;/a\ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Nginx configured with custom X-Served-By header"
